version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.6 # You can adjust the Node.js version as needed

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # Add more cache keys for yarn.lock or other lock files if needed

      - run:
          name: Install Dependencies
          command: npm install # Use yarn if you prefer yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run Tests
          command: npm test # Adjust test command if needed
